spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/senac_pi_4
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
jwt.secret=${JWT_SECRET}
spring.config.import=optional:file:.env[.properties]
mailtrap.api.token=${MAILTRAP_API_TOKEN}
server.port=${PORT:8080}
logging.level.root=INFO
logging.level.br.edu.senac.backend=DEBUG
logging.file.name=logs/backend.log