ALTER TABLE cursos ADD COLUMN IF NOT EXISTS total_semestres INTEGER NOT NULL DEFAULT 1;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS semestre_atual INTEGER NOT NULL DEFAULT 1;
ALTER TABLE solicitacoes ADD COLUMN IF NOT EXISTS semestre INTEGER;
ALTER TABLE regras_atividade ADD COLUMN IF NOT EXISTS limite_horas_semestral INTEGER NOT NULL DEFAULT 0;